version: "3"
services:
  jupyter:
    build: .
    command: /bin/bash -c "/home/pyuser/anaconda/bin/jupyter notebook \
      --notebook-dir=/home/pyuser --ip='*' --port=8080 --no-browser --allow-root"
    volumes:
      - .:/home/pyuser
    ports:
      - "8080:8080"

  jupyter_lab:
    build: .
    command: /bin/bash -c "/home/pyuser/anaconda/bin/jupyter lab \
      --notebook-dir=/home/pyuser --ip='*' --port=8081 --no-browser --allow-root"
    volumes:
      - .:/home/pyuser
    ports:
      - "8081:8081"
