version: "3"
services:
  jupyter:
    build: .
    command: /bin/bash -c "/home/pyuser/anaconda/bin/jupyter notebook --port=8888 --no-browser --ip=127.0.0.1 --allow-root"
    volumes:
      - .:/home/pyuser/notebooks
    ports:
      - "127.0.0.1:8888:8888"
