version: "3"
services:
  jupyter:
    build: .
    command: "/home/pyuser/anaconda/bin/jupyter notebook \
      --notebook-dir=/home/pyuser --ip='*' --port=8080 --no-browser --allow-root"
    volumes:
      - .:/home/pyuser
    ports:
      - "8080:8080"

  jupyter_lab:
    build: .
    command: start-notebook.sh --NotebookApp.notebook_dir=./notebooks
    volumes:
      - .:/home/pyuser
    ports:
      - "8081:8081"
    environment:
      - JUPYTER_ENABLE_LAB=1
